name: Build & Deploy STIP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restore toată soluția, ca să acopere și proiectul de teste
      - name: Restore
        run: dotnet restore ./Simplified-Threat-Intelligence-Platform.sln

      # Build pe Release (fără rebuild la test/publish)
      - name: Build
        run: dotnet build ./Simplified-Threat-Intelligence-Platform.sln -c Release --no-restore

      # Rulează testele xUnit (eșuează pipeline-ul dacă pică)
	- name: Test (run all test projects in the solution)
  	run: dotnet test ./Simplified-Threat-Intelligence-Platform.sln -c Release --no-build --logger "trx;LogFileName=testResults.trx"


      # Publică DOAR proiectul web din root
      - name: Publish
        run: dotnet publish ./Simplified-Threat-Intelligence-Platform.csproj -c Release -o ${{ github.workspace }}/publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ./publish

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_24123497BD77450E9F7B8F65704C6E4A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9CCCBB3BD51A41559C3AB4D68CCD4DFE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2EF8250BEA3E4396B04EAAF51B37E677 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TI'
          slot-name: 'Production'
          package: ./publish
