name: Build & Deploy STIP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: List csproj (debug)
        run: |
          pwd
          find . -maxdepth 4 -type f -name "*.csproj" -print

      - name: Detect web project
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          WEB_CSPROJ=$(grep -Rl '<Project Sdk="Microsoft.NET.Sdk.Web"' --include '*.csproj' . | head -n1 || true)
          if [ -z "$WEB_CSPROJ" ]; then
            WEB_CSPROJ=$(find . -type f -name '*.csproj' ! -iname '*Tests*.csproj' | head -n1 || true)
          fi
          if [ -z "$WEB_CSPROJ" ]; then
            echo "No web project found."
            exit 1
          fi
          echo "Web project: $WEB_CSPROJ"
          echo "web_csproj=$WEB_CSPROJ" >> "$GITHUB_OUTPUT"

      - name: Restore (solution)
        run: dotnet restore ./Simplified-Threat-Intelligence-Platform.sln

      - name: Build (solution)
        run: dotnet build ./Simplified-Threat-Intelligence-Platform.sln -c Release --no-restore

      - name: Test (run all test projects)
        run: dotnet test ./Simplified-Threat-Intelligence-Platform.sln -c Release --no-build --logger "trx;LogFileName=testResults.trx"

      - name: Publish (web project)
        run: dotnet publish "${{ steps.detect.outputs.web_csproj }}" -c Release -o ${{ github.workspace }}/publish --no-build

      - name: Show publish content (debug)
        run: |
          echo "Published files:"
          ls -la ${{ github.workspace }}/publish
          test -f "${{ github.workspace }}/publish/appsettings.json" && echo "appsettings.json present"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ./publish

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_24123497BD77450E9F7B8F65704C6E4A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9CCCBB3BD51A41559C3AB4D68CCD4DFE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2EF8250BEA3E4396B04EAAF51B37E677 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TI'
          slot-name: 'Production'
          package: ./publish
